version: "3"

volumes:
  todo-db-data-dev:
    external: true

services:
  todo-backend:
    build:
      context: .
    container_name: todo-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: todo-app
      POSTGRES_PASSWORD: todo-app
      POSTGRES_PORT: 5432
      POSTGRES_DB: todo-app-dev
      POSTGRES_HOST: todo-db

  todo-db:
    image: postgres:13-alpine
    container_name: todo-db
    ports:
      - "5432:5432"
    volumes:
      - todo-db-data-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: todo-app
      POSTGRES_PASSWORD: todo-app
      POSTGRES_PORT: 5432
      POSTGRES_DB: todo-app-dev

  dbmate:
    container_name: dbmate-dev
    image: amacneil/dbmate
    command: --wait --wait-timeout=15s up
    volumes:
      - ./db:/db
    depends_on:
      - todo-db
    environment:
      DATABASE_URL: postgres://todo-app:todo-app@todo-db:5432/todo-app-dev?sslmode=disable
